package donde_pablito;

import java.awt.Color;

public class MenuPrincipal extends javax.swing.JFrame {
    
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(img_frutas, "src/img/frutas2.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        bt_cerrar = new javax.swing.JLabel();
        img_frutas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb_comprar = new javax.swing.JLabel();
        lb_añadir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiendita OXXO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_logo.setBackground(new java.awt.Color(255, 255, 255));
        img_logo.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        img_logo.setForeground(new java.awt.Color(255, 255, 255));
        img_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo1.png"))); // NOI18N
        jPanel1.add(img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 260, 230));

        bt_cerrar.setBackground(new java.awt.Color(255, 255, 255));
        bt_cerrar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bt_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cerrar.setText("X");
        bt_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cerrar.setOpaque(true);
        bt_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_cerrarMouseExited(evt);
            }
        });
        jPanel1.add(bt_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, -1));

        img_frutas.setBackground(new java.awt.Color(0, 153, 153));
        img_frutas.setOpaque(true);
        jPanel1.add(img_frutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        lb_comprar.setBackground(new java.awt.Color(0, 153, 153));
        lb_comprar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_comprar.setForeground(new java.awt.Color(255, 255, 255));
        lb_comprar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_comprar.setText("COMPRAR");
        lb_comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_comprar.setOpaque(true);
        lb_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_comprarMouseClicked(evt);
            }
        });
        jPanel1.add(lb_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 150, 70));

        lb_añadir.setBackground(new java.awt.Color(0, 153, 153));
        lb_añadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_añadir.setForeground(new java.awt.Color(255, 255, 255));
        lb_añadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_añadir.setText("AÑADIR");
        lb_añadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_añadir.setOpaque(true);
        lb_añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_añadirMouseClicked(evt);
            }
        });
        jPanel1.add(lb_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("DondePablito");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int xMouse, yMouse;
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void bt_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bt_cerrarMouseClicked

    private void lb_añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_añadirMouseClicked
        new AñadirStock().setVisible(true);
    }//GEN-LAST:event_lb_añadirMouseClicked

    private void lb_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_comprarMouseClicked
        new Venta().setVisible(true);
    }//GEN-LAST:event_lb_comprarMouseClicked

    private void bt_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarMouseEntered
        bt_cerrar.setBackground(Color.red);
        bt_cerrar.setForeground(Color.white);
    }//GEN-LAST:event_bt_cerrarMouseEntered

    private void bt_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarMouseExited
        bt_cerrar.setBackground(Color.white);
        bt_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_bt_cerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_cerrar;
    private javax.swing.JLabel img_frutas;
    private javax.swing.JLabel img_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_añadir;
    private javax.swing.JLabel lb_comprar;
    // End of variables declaration//GEN-END:variables
}
